### ISSUE TITLE
Debian Installation Issues

### ISSUE THREAD

**Issue by jeevisonline** [amidaware/tacticalrmm#1024]
**Server Info (please complete the following information):**
 - OS: Debian 11.2.0
 - Browser: Firefox
 - RMM Version (as shown in top left of web UI):12.0/12.1

**Installation Method:**
  - Standard

**Agent Info (please complete the following information):**
- Agent not deployable

**Describe the bug**
I get the error 
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.xxx.ca/checkcreds/. (Reason: CORS header “Access-Control-Allow-Origin” missing).`
When trying to log into a freshly installed server.

**To Reproduce**
1. Install Debian 11.2.0
2. Using the Installation method, copy and paste the commands from the Traditional Installer Guide.(No firewall was installed/used)
3. Enter information as required into the script.
4. Upon completion, attempt to log into web portal.

**Expected behavior**
No issues expected on a fresh installation on Debian.  This issue does not occur on Ubuntu.

**Screenshots**
![image](https://user-images.githubusercontent.com/97365870/160249080-57a3b37a-3227-473f-b0a5-177124bbadeb.png)

**Additional context**
Running the command `bash -x install.sh 2>&1 | tee install.log`, I noticed errors in the output file.
Wh1te has this file on discord.
Relevant Information:
Mesh Central Starts, running on port 4430 aliased to port 443, NATS gets enabled, environment variables are set, 
Then i start getting syntax errors.
```SyntaxError: unterminated string literal (detected at line 28)
+ python manage.py reload_nats
Traceback (most recent call last):
  File "/rmm/api/tacticalrmm/manage.py", line 21, in <module>
    main()
  File "/rmm/api/tacticalrmm/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/rmm/api/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/rmm/api/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 363, in execute
    settings.INSTALLED_APPS
  File "/rmm/api/env/lib/python3.10/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/rmm/api/env/lib/python3.10/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/rmm/api/env/lib/python3.10/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/rmm/api/tacticalrmm/tacticalrmm/__init__.py", line 3, in <module>
    from .celery import app as celery_app
  File "/rmm/api/tacticalrmm/tacticalrmm/celery.py", line 13, in <module>
    backend="redis://" + settings.REDIS_HOST,
  File "/rmm/api/env/lib/python3.10/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/rmm/api/env/lib/python3.10/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/rmm/api/env/lib/python3.10/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/rmm/api/tacticalrmm/tacticalrmm/settings.py", line 56, in <module>
    from .local_settings import *
  File "/rmm/api/tacticalrmm/tacticalrmm/local_settings.py", line 28
    MESH_TOKEN_KEY = "Resetting events indexes...```

**Comment by silversword411** [comment]
Cross origin I think is you trying to cross URL's and getting a failure. You reinstall fresh a new installation. Just installed a new deb server the other day without issues

**Comment by jeevisonline** [comment]
Yeah, I looked at this with Wh1te.  He can't reproduce it with the same ISO and platform.  Going to assume that it's something with my setup unless it happens to someone else.  I will close this for now.
