### ISSUE TITLE
Entering a comma in the hours number in the download agent dialog generates an error

### ISSUE THREAD

**Issue by NiceGuyIT** [amidaware/tacticalrmm#1461]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS
 - Browser: Firefox 110.0 (64-bit)
 - RMM Version (as shown in top left of web UI): v0.15.7

**Installation Method:**
  - [x] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): v2.4.4
- Agent OS: Windows 10 Pro, 64 bit v21H2 (build 19044.2728)

**Describe the bug**
The "time expiration (hours)" field expects a number but does not accept numbers with a comma.

**To Reproduce**
1. Go to Agents > Install Agent
2. Enter a number with a comma in the token expiration field.
3. Click "Generate and Download exe" and you'll get an error.

**Expected behavior**
I would expect the system to accept numbers with commas. Ideally, this should also be locale aware with the possibility of accepting periods instead of commas.

**Screenshots**
N/A

**Additional context**
The POST request does not have the token value. This implies the frontend is invalidating the input.

POST sent to `https://api.a8n.tools/agents/installer/`:
```json
{
  "agenttype": "workstation",
  "api": "https://api.a8n.tools",
  "client": 6,
  "expires": "",
  "fileName": "trmm-help-onboarding-workstation-amd64.exe",
  "goarch": "amd64",
  "installMethod": "exe",
  "ping": 0,
  "plat": "windows",
  "power": 0,
  "rdp": 0,
  "site": 9
}
```

Stack trace from `/rmm/api/tacticalrmm/tacticalrmm/private/log/django_debug.log`:
```text
[23/Mar/2023 18:57:25] ERROR [django.request:241] Internal Server Error: /agents/installer/
Traceback (most recent call last):
  File "/rmm/api/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/rmm/api/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/rmm/api/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/rmm/api/env/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/rmm/api/env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/rmm/api/env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/rmm/api/env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/rmm/api/env/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/rmm/api/env/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/rmm/api/tacticalrmm/agents/views.py", line 563, in install_agent
    user=installer_user, expiry=dt.timedelta(hours=request.data["expires"])
TypeError: unsupported type for timedelta hours component: str
```

**Comment by wh1te909** [comment]
good timing lol was about to do a release. looks like this is only an issue on firefox, chrome doesn't let u enter a comma, so frontend validation broken on firefox but we shouldn't be relying just on frontend validation so I added a quick backend validation for now, need to rework later
