### ISSUE TITLE
0.17.5 fails to install properly and requires some manual changes to shape it

### ISSUE THREAD

**Issue by optiproplus** [amidaware/tacticalrmm#1764]
**Server Info (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS
 - RMM Version (as shown in top left of web UI): 0.17.5

**Installation Method:**
  - [x] Standard
  - [ ] Docker

**Describe the bug**

1. it's a fresh-new ubuntu vps
2. our first installation somehow 'completed' however it showed an error stating during install:
Creating meshcentral account and group
--------------------------------------------------------------------------------
Done.
Done. This command will only work if MeshCentral is stopped.
Mesh Central not ready yet...
ok mesh//e4E4O@9HJQBwrYZfcVt64rDPC9a5LJCFJwNQ3nrZ04mNHnEboMfXnv7ok1uziQ7j
Created symlink /etc/systemd/system/multi-user.target.wants/nats.service → /etc/systemd/system/nats.service.
Traceback (most recent call last):
  File "/rmm/api/env/lib/python3.11/site-packages/redis/connection.py", line 264, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rmm/api/env/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/rmm/api/env/lib/python3.11/site-packages/redis/connection.py", line 265, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/rmm/api/env/lib/python3.11/site-packages/redis/connection.py", line 627, in _connect
    raise err
  File "/rmm/api/env/lib/python3.11/site-packages/redis/connection.py", line 615, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/rmm/api/tacticalrmm/manage.py", line 21, in <module>
    main()
  File "/rmm/api/tacticalrmm/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/rmm/api/env/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/rmm/api/env/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/rmm/api/env/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/rmm/api/env/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rmm/api/tacticalrmm/core/management/commands/initial_db_setup.py", line 15, in handle
    CoreSettings().save()
  File "/rmm/api/tacticalrmm/core/models.py", line 111, in save
    cache.delete(CORESETTINGS_CACHE_KEY)
  File "/rmm/api/env/lib/python3.11/site-packages/django/core/cache/backends/redis.py", line 199, in delete
    return self._cache.delete(key)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/rmm/api/env/lib/python3.11/site-packages/django/core/cache/backends/redis.py", line 119, in delete
    return bool(client.delete(key))
                ^^^^^^^^^^^^^^^^^^
  File "/rmm/api/env/lib/python3.11/site-packages/redis/commands/core.py", line 1712, in delete
    return self.execute_command("DEL", *names)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rmm/api/env/lib/python3.11/site-packages/redis/client.py", line 533, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rmm/api/env/lib/python3.11/site-packages/redis/connection.py", line 1291, in get_connection
    connection.connect()
  File "/rmm/api/env/lib/python3.11/site-packages/redis/connection.py", line 270, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
Reloading NATs configuration...
NATs configuration reloaded

and the installation was completely broken, however when we tried to launch redis, it was working fine
so we had to rollback everything except redis and re-start the installation from scratch
3. after install it was still unusable until we find out that 'TacticalRMM' group was not created inside the mesh
4. i don't know why, but mesh web interface just doesn't work while trying to push 'add group' button, so we had to create it manually via mesh cli
5. there was an error in nginx rmm.conf in /natws section - until after we've put proxy_set_header Upgrade "websocket" - we were getting 'error in Upgrade header' from nats server

**Comment by dinger1986** [comment]
where is the vps hosted? is it a vps and not LXC? what version of Ubuntu?

**Comment by wh1te909** [comment]
I just tested a fresh install on ubuntu 22.04.3 and not able to reproduce, install works fine. Do not attempt to manually change or edit things. If install didn't work you need to wipe and try again.
